---
# ============================================================================
# Step 1: Build Docker image locally on control node
# ============================================================================
- name: Build Docker image locally on control node
  hosts: localhost
  become: true
  tasks:

    - name: Ensure Docker is installed (Ubuntu)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      ignore_errors: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Build Docker image locally
      command: docker build -t mcm/web-app:latest "{{ playbook_dir }}/Docker"
      args:
        chdir: "{{ playbook_dir }}/Docker"

    - name: Save Docker image as tarball
      command: docker save -o "{{ playbook_dir }}/mcm_webapp.tar" mcm/web-app:latest

    - name: Ensure tarball is readable
      file:
        path: "{{ playbook_dir }}/mcm_webapp.tar"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'

# ============================================================================
# Step 2: Deploy Docker image to Ubuntu and CentOS nodes
# ============================================================================
- name: Deploy Docker image to managed nodes
  hosts: Ubuntu, CentOS
  become: true
  tasks:

    - name: Install Docker (Ubuntu)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      ignore_errors: yes

    - name: Install Docker (CentOS)
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      when: ansible_distribution == "CentOS"
      ignore_errors: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Copy Docker image tarball to managed node
      copy:
        src: "{{ playbook_dir }}/mcm_webapp.tar"
        dest: /tmp/mcm_webapp.tar
        mode: '0644'

    - name: Load Docker image on managed node
      command: docker load -i /tmp/mcm_webapp.tar

    - name: Run Docker container
      docker_container:
        name: magboo_webapp
        image: mcm/web-app:latest
        ports:
          - "8080:80"
        state: started

